apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    user: assistant
    password: sDc7t4RefG  # Cambia esto por la contraseña correcta
    database: cooking_recipe_assistant
    basicAuth: false
    jsonData:
      sslmode: disable

